name: main-pr
on:
  pull_request:
    branches:
      - main
    types:
      - ready_for_review

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        run: |
          echo "Hello"
      - name: step two
        run: echo "World"

  job-two:
    runs-on: ubuntu-latest
    steps:
      - name: step two
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          # TEMP Check environment
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
          echo "EVENT_NAME=${EVENT_NAME}"
          echo "PR_TITLE=${PR_TITLE}"
    
    
