name: main-push
on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test-string: "my test string"
      message-or-title: ${{ steps.determine-message-or-title.outputs.MESSAGE_OR_TITLE }}
    steps:
      - name: Foo
        id: determine-message-or-title
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] ; then
            MSG_TITLE="${{ github.event.pull_request.title }}"
          else
            MSG_TITLE="${{ github.event.head_commit.message }}"
          fi
          echo "MESSAGE_OR_TITLE=${MSG_TITLE}" >> $GITHUB_OUTPUT
        shell: bash

  job-one:
    needs: [setup]
    #if: false  # Temporarily disable.
    runs-on: ubuntu-latest
    env:
      MESSAGE_OR_TITLE: ${{ needs.setup.outputs.message-or-title }}
    steps:
      - name: step one
        run: |
          echo "${MESSAGE_OR_TITLE}"
          echo "Hello"
      - name: step two
        run: echo "World"

  job-two:
    needs: [setup, job-one]
    # when none of the needed jobs fail or are cancelled (skipped or successful jobs are ok).
    # And the [job-two] tag is specified.
    if: | 
      always() && !failure() && !cancelled()
      && contains(github.event.head_commit.message, '[job-two]')
    uses: ./.github/workflows/env.yml
    with:
      env: "a"
      message-or-title: ${{ needs.setup.outputs.message-or-title }}
  job-three:
    needs: [setup, job-one, job-two]
    # when none of the needed jobs fail or are cancelled (skipped or successful jobs are ok).
    # And the [job-two] or [job-three] tag is specified.
    if: | 
      always() && !failure() && !cancelled()
      && ( contains(github.event.head_commit.message, '[job-two]') || contains(github.event.head_commit.message, '[job-three]') )
    runs-on: ubuntu-latest
    steps:
      - name: step two
        run: echo "Job 3."

  final-job:
    needs: [setup, job-one, job-two, job-three]
    if: always() && !failure() && !cancelled() # when none of the needed jobs fail or are cancelled (skipped or successful jobs are ok).
    runs-on: ubuntu-latest
    steps:
      - name: step two
        run: echo "Final Job."
#  job-three:
#    if: contains(github.event.head_commit.message, '[do-something]') || contains(github.event.head_commit.message, '[do-something-else]')
#    needs: job-two
#    uses: ./.github/workflows/job_three.yml
#    with:
#      env: "a"

#  # Split job into steps that only run based on a condition.  This allows the job to be a dependency of the next job even if the tasks do not need to run.
# Problems running reusable workfloes from steps.
#  conditional-tasks:
#    needs: job-two
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v3
#      - name: task-one
#        if: contains(github.event.head_commit.message, '[run-both]')
#        uses: ./.github/workflows/task_one.yml
#        with:
#          env: "a"
#      - name: task-two
#        if: contains(github.event.head_commit.message, '[run-both]') || contains(github.event.head_commit.message, '[run-two]')
#        uses: ./.github/workflows/task_one.yml
#        with:
#          env: "a"

