name: Task One
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Task One - Step One
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "EVENT_NAME=${EVENT_NAME}"
        shell: bash
